### PR TITLE
Added April 6th 2022 event

### PR DESCRIPTION
**Pull request by malderete**
- Added April event @ KPN

# Latest event
Screenshot 2022-03-31 at 16 18 47

# Event details
Screenshot 2022-03-31 at 16 18 56

### CODE REVIEW

**Comment by gilgamezh** [comment]
@malderete the build is failing for some reason.  Maybe it's ok to merge?

**Comment by malderete** [comment]
@gilgamezh previous PR for March event had the same issue, it looks like the job is not working properly... I'ds say merge it :)
Then we can look at the CI job.

**Comment by 1oglop1** [comment]
@malderete PR preview is failing because the branch is opened from a fork and not this repository, therefore your fork does not have an access to the secrets.
I'd recommend creating a branch in this repo instead of a fork!

**Comment by malderete** [comment]
@1oglop1 thanks! I've supposed it was related to secrets.
As you can see the event is valid and it compiles in pelican, so we could merge it.

I can not create a branch in this repo since I don't have permissions to push here.

@gilgamezh , @1oglop1 let me know what you prefer :)

**Comment by 1oglop1** [comment]
@malderete Your invitation is still pending (means you did not accept it). I'm fine with merging this.

**Pull request merged**
